package com.example.venu.core.core_data.repository

import com.example.venu.core.core_domain.model.Event
import com.example.venu.core.core_domain.repository.EventRepository
import com.example.venu.core.core_domain.repository.ListType
import com.example.venu.core.core_domain.repository.ListsRepository

class InMemoryListsRepository(
    private val eventRepo: EventRepository
) : ListsRepository {

    private val want = LinkedHashSet<String>()
    private val went = LinkedHashSet<String>()
    private val toReview = LinkedHashSet<String>()

    private val customLists = linkedMapOf<String, LinkedHashSet<String>>()

    // for UI to display which custom list a card is saved to
    private val customListNames = linkedMapOf<String, String>()

    override fun getList(type: ListType): List<Event> {
        val ids = when (type) {
            ListType.WantToGo -> want
            ListType.AlreadyWent -> went
            ListType.ToReview -> toReview
            is ListType.Custom -> customLists[type.id] ?: linkedSetOf()
        }
        return ids.mapNotNull { eventRepo.getEventById(it) }
    }

    override fun addToList(type: ListType, eventId: String) {
        setFor(type).add(eventId)
    }

    override fun removeFromList(type: ListType, eventId: String) {
        setFor(type).remove(eventId)
    }

    override fun moveEvent(eventId: String, from: ListType, to: ListType) {
        setFor(from).remove(eventId)
        setFor(to).add(eventId)
    }

    override fun isInList(type: ListType, eventId: String): Boolean {
        return setFor(type).contains(eventId)
    }

    override fun isSaved(eventId: String): Boolean {
        return want.contains(eventId) ||
                went.contains(eventId) ||
                toReview.contains(eventId) ||
                customLists.values.any { it.contains(eventId) }
    }

    override fun toggleWantToGo(eventId: String) {
        if (want.contains(eventId)) { // If it's already saved, unsave it
            want.remove(eventId)
        } else {
            want.add(eventId) // else, save it
        }
    }

    override fun createCustomList(name: String): ListType.Custom {
        val id = name
            .trim()
            .lowercase()
            .replace("\\s+".toRegex(), "_")

        customListNames[id] = name // set value (name) to key (id--generated by trimming name)
        customLists.putIfAbsent(id, linkedSetOf())

        return ListType.Custom(id, name)
    }

    override fun deleteCustomList(listId: String) {
        customLists.remove(listId)
        customListNames.remove(listId)
    }

    override fun getAllLists(): List<ListType> {
        val builtIns = listOf(
            ListType.WantToGo,
            ListType.AlreadyWent,
            ListType.ToReview
        )

        val customs = customListNames.map { (id, name) ->
            ListType.Custom(id = id, name = name)
        }

        return builtIns + customs
    }

    private fun setFor(type: ListType): MutableSet<String> {
        return when (type) {
            ListType.WantToGo -> want
            ListType.AlreadyWent -> went
            ListType.ToReview -> toReview
            is ListType.Custom -> customLists.getOrPut(type.id) { linkedSetOf() }
        }
    }
}